title: "Cròniques del Setè Mar"
description: "Campanya, personatges, naus i relats del Setè Mar."
lang: ca
baseurl: "/diaridenreiv"
url: ""

markdown: kramdown
kramdown:
  input: GFM

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - mon/personatges/*/fitxa.yml
  - mon/personatges/*/descripcio.yml
  - mon/personatges/*/imatge-inicial.*
  - mon/naus/*/canon.md
  - mon/llocs/*/canon.md
  - mon/objectes/*/canon.md
